Repository kingsmen732/portfolio, pull requests merged in 2024-10, with the labels that each got.

#11 Update packages to latest versions
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#14 Added all the experiences tiles and also added +1 year experience tile
  src/assets/experience/+1.svg
  src/assets/experience/+2.svg
  src/assets/experience/+3.svg
  src/assets/experience/+4.svg
  src/assets/experience/+5.svg
  src/assets/experience/+6.svg
  src/assets/experience/Advanced.svg
  src/assets/experience/Fresher.svg
  src/assets/experience/Intermediate.svg
  src/assets/experience/Rookie.svg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#20 Adding footer component to the MainContainer
  src/components/Footer.js
  src/components/MainContainer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 Update index.css
  src/index.css
Labels: hacktoberfest

#31 added project modals
  src/assets/cross.svg
  src/assets/internet.svg
  src/components/BentoLayout.js
  src/components/constants/project.js
  src/components/modals/ProjectModal.jsx
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#35 Update README.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 Revert "Update README.md"
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Non tech

#38 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Non tech

#40 Added feature of dark and light mode
  package-lock.json
  src/App.css
  src/App.js
  src/components/BentoLayout.js
  src/components/MainContainer.js
  src/components/ProfileSidebar.js
  tailwind.config.js
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#42 Corrected Resume link
  src/profileconfig.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#44 fixed Footer in Dark mode
  package.json
  src/components/BentoLayout.js
  src/components/Footer.js
  src/index.js
Labels: enhancement, hacktoberfest

#45 Added Preview Button with Review Slider
  package-lock.json
  package.json
  src/components/constants/project.js
  src/components/modals/Project.jsx
  src/components/modals/ProjectModal.jsx
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#53 [Fixed]: Mode button no longer covered
  src/components/BentoLayout.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#56 Changing mail icon
  src/assets/mail.png
  src/assets/old_mail.png
Labels: documentation, hacktoberfest, Non tech

#58 'Who Am I?' Color Fixed When Switching to Light/Dark Mode
  src/components/BentoLayout.js
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#67 Update README.md
  README.md
Labels: enhancement, hacktoberfest

#69 Changing CSS of Project Modal
  src/components/BentoLayout.js
  src/components/modals/ProjectModal.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#50 Added Contact me form
  .gitignore
  src/assets/contact.jpg
  src/components/BentoLayout.js
  src/components/ContactMeForm.js
  src/components/modals/ContactModal.jsx
  src/profileconfig.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
